###########################################################
# Site settings
title: Aurelie Jodelle Kemme
url: "http://Aurelie-Jodelle.github.io"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
  Welcome to my website.

# Your information
email: jodelle.kemme@aims-cameroon.org
author: Aurelie Jodelle Kemme
avatar: "https://github.com/aureliejodellekemme/Aurelie-Jodelle.github.io/blob/gh-pages/photos/aurelie_portrait.jpg?raw=true"
profile: I'm a next Einstein Mathematicians and Cameroonian.
#twitter_username: twitter_username
#github_username:  github_username
profile_links:
  Email: "mailto:jodelle.kemme@aims-cameroon.org"
  GitHub: "https://github.com/aureliejodellekemme"
  Linkedin: "https://linkedin.com/in/aurélie-jodelle-kemme-5a0754119"
  CV: "../documents/CV_Jodelle_Kemme_May.pdf"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
disqus_shortname: personal-website-9uunp9kwad  # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Projects: /category/
  
    Publications: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

    values:
      layout: "post"
      permalink: /:aureliejodellekemme/

  # for multilingual posts
  - scope:
      # to separate language posts folders
      path: "*/_posts"
    values:
      hidden: true
      layout: "post"
      permalink: /:aureliejodellekemme/

  # example: enable setting for all pages. You may still need to enable some setting from _data/conf/posts.yml or _data/conf/main.yml
  # - scope:
  #     # an empty string here means all files in the project
  #     path: ""
  #   values:
  #     image_viewer_on: true
  #     image_lazy_loader_on: true

###########################################################
# Markdown Options (https://jekyllrb.com/docs/configuration/markdown/)
# Configuring Jekyll in your GitHub Pages site (https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/about-github-pages-and-jekyll)
###########################################################
# This is default for GitHub Pages sites and cannot be changed.
highlighter: rouge
markdown: kramdown
kramdown:
  # This is default for GitHub Pages sites and cannot be changed.
  syntax_highlighter: rouge

###########################################################
# Plugins (Plugins supported by GitHub Pages https://pages.github.com/versions/)
###########################################################
plugins:
  - jekyll-paginate
  - jekyll-redirect-from

# since GitHub Pages runs jekyll with "--safe" flag, we need to add supported plugins in here. (only github supported plugins are allowed)
whitelist:
  - jekyll-paginate
  - jekyll-redirect-from

###########################################################
# jekyll-paginate (https://jekyllrb.com/docs/pagination/)
###########################################################
paginate_path: "/tabs/blog/:num"
# number of post per page
# make sure this matches with post_query_paginator_post_per_page in _data/conf/posts.yml
paginate: 5

###########################################################
# jekyll-redirect-from (https://github.com/jekyll/jekyll-redirect-from)
###########################################################
redirect_from:
  # Disabling generation of redirects.json
  json: false

###########################################################
# html compression (https://jch.penibelst.de)
###########################################################
compress_html:
  clippings: all
  comments: all
  #endings: all
  profile: false
  blanklines: false
  ignore:
    # disable this feature for development env.
    envs: [development]

###########################################################
# js compression (for removing comments(/**/only), line breaks and spaces)
# for debugging js files, simply set linebreak_and_space: false (in production env, this will be enabled automatically)
# for more info about environments (https://jekyllrb.com/docs/configuration/environments/)
###########################################################
compress_js:
  # enable or disable line breaks and space removal feature for development env.
  linebreak_and_space: false
  # disable this feature entirely for development or production env.
  #ignore: development

###########################################################
# Sass (https://jekyllrb.com/docs/assets/)
###########################################################
sass:
  sass_dir: assets/_scss
  # enable css compression
  style: compressed

###########################################################
# Exclude these files or folders from production site
###########################################################
exclude: ["Gemfile*", "README*", "LICENSE", "docs"]
